# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBnXQOcU-zDvT_sxQNjMUAhhkURtZXGw
"""

import random

# 🎯 Workout Plans based on Goals, Levels, and Equipment
workout_plans = {
    "Muscle Gain": {
        "Beginner": {
            "Gym": ["Squats", "Bench Press", "Lat Pulldown", "Bicep Curls", "Leg Press"],
            "Home": ["Push-ups", "Bodyweight Squats", "Dumbbell Rows", "Lunges"]
        },
        "Intermediate": {
            "Gym": ["Pull-ups", "Overhead Press", "Romanian Deadlifts", "Chest Fly"],
            "Home": ["Handstand Push-ups", "Bulgarian Split Squats", "Dumbbell Deadlifts"]
        },
        "Advanced": {
            "Gym": ["Heavy Deadlifts", "Weighted Dips", "Power Cleans"],
            "Home": ["One-arm Push-ups", "Pistol Squats", "Planche Push-ups"]
        }
    },
    "Fat Loss": {
        "Beginner": {
            "Gym": ["Jump Rope", "Treadmill Walk", "Battle Ropes"],
            "Home": ["Jump Rope", "Burpees", "Jogging"]
        },
        "Intermediate": {
            "Gym": ["HIIT Workout", "Boxing Drills", "Kettlebell Swings"],
            "Home": ["Mountain Climbers", "Jumping Lunges", "Plank to Push-Up"]
        },
        "Advanced": {
            "Gym": ["Sprint Intervals", "Sled Pushes", "Burpee Pull-ups"],
            "Home": ["Sprint Drills", "Explosive Jump Squats", "Jump Rope Speed Sets"]
        }
    },
    "Strength & Endurance": {
        "Beginner": {
            "Gym": ["Deadlifts", "Farmers Walk", "Kettlebell Swings"],
            "Home": ["Push-ups", "Squats", "Plank Hold"]
        },
        "Intermediate": {
            "Gym": ["Front Squats", "Sled Push", "Dumbbell Snatches"],
            "Home": ["Jump Squats", "Burpees", "Resistance Band Rows"]
        },
        "Advanced": {
            "Gym": ["Power Cleans", "Tire Flips", "Atlas Stones"],
            "Home": ["One-arm Push-ups", "Pistol Squats", "Weighted Pull-ups"]
        }
    }
}

# 🍎 Diet Plans based on Goals & Preferences
diet_plans = {
    "Muscle Gain": {
        "Vegetarian": ["Oatmeal with Nuts", "Lentil Soup", "Tofu Stir Fry", "Quinoa Salad"],
        "Non-Vegetarian": ["Chicken Breast & Rice", "Grilled Salmon", "Eggs & Avocado"]
    },
    "Fat Loss": {
        "Vegetarian": ["Green Smoothie", "Grilled Paneer Salad", "Chickpea Bowl"],
        "Non-Vegetarian": ["Grilled Chicken Salad", "Boiled Eggs & Spinach", "Fish & Steamed Veggies"]
    },
    "Strength & Endurance": {
        "Vegetarian": ["Chia Pudding", "Protein Smoothie", "Sweet Potato Bowl"],
        "Non-Vegetarian": ["Lean Beef & Rice", "Tuna Sandwich", "Chicken Stir Fry"]
    }
}

# 🏋️ Function to get a workout plan
def get_workout(goal, level, equipment):
    if goal in workout_plans and level in workout_plans[goal] and equipment in workout_plans[goal][level]:
        return workout_plans[goal][level][equipment]
    else:
        return ["⚠️ No workout plan found for the given selection. Please check your inputs."]

# 🍽️ Function to get a diet plan
def get_diet(goal, preference):
    if goal in diet_plans and preference in diet_plans[goal]:
        return diet_plans[goal][preference]
    else:
        return ["⚠️ No diet plan available for the given selection. Please check your inputs."]

# 🌟 User Input with Validation
print("🏋️ AI Fitness & Diet Planner 🍎")

valid_goals = list(workout_plans.keys())
goal = input(f"🎯 Enter your goal {valid_goals}: ").strip()
while goal not in valid_goals:
    print("❌ Invalid choice! Please choose from the available goals.")
    goal = input(f"🎯 Enter your goal {valid_goals}: ").strip()

valid_levels = ["Beginner", "Intermediate", "Advanced"]
level = input(f"📊 Enter your fitness level {valid_levels}: ").strip()
while level not in valid_levels:
    print("❌ Invalid choice! Please choose from the available levels.")
    level = input(f"📊 Enter your fitness level {valid_levels}: ").strip()

valid_equipment = ["Gym", "Home"]
equipment = input(f"🏋️ Where will you train? {valid_equipment}: ").strip()
while equipment not in valid_equipment:
    print("❌ Invalid choice! Please choose from 'Gym' or 'Home'.")
    equipment = input(f"🏋️ Where will you train? {valid_equipment}: ").strip()

valid_diet = ["Vegetarian", "Non-Vegetarian"]
diet_preference = input(f"🍽️ Choose your diet preference {valid_diet}: ").strip()
while diet_preference not in valid_diet:
    print("❌ Invalid choice! Please choose from 'Vegetarian' or 'Non-Vegetarian'.")
    diet_preference = input(f"🍽️ Choose your diet preference {valid_diet}: ").strip()

# 🔥 Get Workout & Diet Plans
workout_plan = get_workout(goal, level, equipment)
diet_plan = get_diet(goal, diet_preference)

# 📌 Display Results
print("\n🏋️ Your Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")

print("\n🍽️ Your Diet Plan:")
for meal in diet_plan:
    print(f"- {meal}")

print("\n💪 Stay fit & healthy! 🚀")