# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9vKxNkGAzm8QKP9Dt4gq5vwAOQeDqVV
"""

import pandas as pd

# Create a dataset of workout plans
workout_data = pd.DataFrame({
    "Goal": ["Muscle Gain", "Fat Loss", "Endurance"],
    "Fitness Level": ["Beginner", "Intermediate", "Advanced"],
    "Equipment": ["Gym", "Home", "Gym"],
    "Workout Plan": [
        ["Squats", "Deadlifts", "Bench Press"],
        ["Jump Rope", "HIIT", "Burpees"],
        ["Cycling", "Swimming", "Long-distance Running"]
    ]
})

# Display dataset
workout_data
import random

def get_workout(goal, level, equipment):
    # Filter the dataset based on user input
    result = workout_data[
        (workout_data["Goal"] == goal) &
        (workout_data["Fitness Level"] == level) &
        (workout_data["Equipment"] == equipment)
    ]

    # Return a workout plan if found, else return a default plan
    if not result.empty:
        return random.choice(result["Workout Plan"].values[0])
    else:
        return ["Push-ups", "Planks", "Bodyweight Squats"]  # Default workout

# Example input
goal = "Fat Loss"
level = "Intermediate"
equipment = "Home"

# Get AI-generated workout plan
workout_plan = get_workout(goal, level, equipment)
print("🏋️ Recommended Workout Plan:", workout_plan)
# Get user input
goal = input("Enter your fitness goal (Muscle Gain/Fat Loss/Endurance): ")
level = input("Enter your fitness level (Beginner/Intermediate/Advanced): ")
equipment = input("Enter available equipment (Gym/Home): ")

# Get recommended workout
workout_plan = get_workout(goal, level, equipment)

# Display output
print("\n🏋️ Your Personalized Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")

import random

# Define a simple workout plan dictionary
workout_plans = {
    ("Muscle Gain", "Beginner", "Gym"): ["Squats", "Bench Press", "Deadlifts"],
    ("Muscle Gain", "Intermediate", "Gym"): ["Pull-ups", "Overhead Press", "Leg Press"],
    ("Muscle Gain", "Advanced", "Gym"): ["Heavy Deadlifts", "Weighted Dips", "Front Squats"],

    ("Fat Loss", "Beginner", "Home"): ["Jump Rope", "Bodyweight Squats", "Burpees"],
    ("Fat Loss", "Intermediate", "Home"): ["HIIT Workout", "Mountain Climbers", "Jumping Lunges"],
    ("Fat Loss", "Advanced", "Home"): ["Sprint Intervals", "Kettlebell Swings", "Box Jumps"],

    ("Endurance", "Beginner", "Gym"): ["Treadmill Walk", "Rowing Machine", "Cycling"],
    ("Endurance", "Intermediate", "Gym"): ["Running", "Elliptical Trainer", "Swimming"],
    ("Endurance", "Advanced", "Gym"): ["Marathon Training", "Stair Climber", "Long-distance Swimming"]
}

# Function to get a workout plan based on user input
def get_workout(goal, level, equipment):
    return workout_plans.get((goal, level, equipment), ["Push-ups", "Planks", "Bodyweight Squats"])  # Default

# Get user input
goal = input("Enter your fitness goal (Muscle Gain / Fat Loss / Endurance): ").strip()
level = input("Enter your fitness level (Beginner / Intermediate / Advanced): ").strip()
equipment = input("Enter available equipment (Gym / Home): ").strip()

# Get and display workout
workout_plan = get_workout(goal, level, equipment)

print("\n🏋️ Your Personalized Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")

import random

# Expanded workout plans with more categories
workout_plans = {
    # Muscle Gain
    ("Muscle Gain", "Beginner", "Gym"): ["Squats", "Bench Press", "Deadlifts", "Lat Pulldown", "Bicep Curls"],
    ("Muscle Gain", "Intermediate", "Gym"): ["Pull-ups", "Overhead Press", "Leg Press", "Dumbbell Rows", "Chest Fly"],
    ("Muscle Gain", "Advanced", "Gym"): ["Heavy Deadlifts", "Weighted Dips", "Front Squats", "Snatch", "Power Cleans"],

    # Fat Loss
    ("Fat Loss", "Beginner", "Home"): ["Jump Rope", "Bodyweight Squats", "Burpees", "Jogging", "Lunges"],
    ("Fat Loss", "Intermediate", "Home"): ["HIIT Workout", "Mountain Climbers", "Jumping Lunges", "Plank to Push-Up"],
    ("Fat Loss", "Advanced", "Home"): ["Sprint Intervals", "Kettlebell Swings", "Box Jumps", "Battle Ropes", "Tuck Jumps"],

    # Endurance Training
    ("Endurance", "Beginner", "Gym"): ["Treadmill Walk", "Rowing Machine", "Cycling", "Jump Rope"],
    ("Endurance", "Intermediate", "Gym"): ["Running", "Elliptical Trainer", "Swimming", "Rowing Machine"],
    ("Endurance", "Advanced", "Gym"): ["Marathon Training", "Stair Climber", "Long-distance Swimming", "Sprint Intervals"],

    # Flexibility & Mobility
    ("Flexibility", "Beginner", "Home"): ["Basic Yoga Poses", "Neck & Shoulder Stretch", "Seated Forward Bend"],
    ("Flexibility", "Intermediate", "Home"): ["Downward Dog", "Lunging Hip Flexor Stretch", "Cobra Pose"],
    ("Flexibility", "Advanced", "Home"): ["Pigeon Pose", "Frog Stretch", "Full Bridge"],

    # Sports-Specific Training
    ("Sports Training", "Beginner", "Gym"): ["Agility Ladder Drills", "Box Drills", "Resistance Band Drills"],
    ("Sports Training", "Intermediate", "Gym"): ["Plyometric Jumps", "Sprint Drills", "Medicine Ball Throws"],
    ("Sports Training", "Advanced", "Gym"): ["Explosive Sprinting", "Depth Jumps", "Olympic Weightlifting"],

    # Strength Training
    ("Strength Training", "Beginner", "Home"): ["Push-ups", "Bodyweight Squats", "Planks", "Lunges"],
    ("Strength Training", "Intermediate", "Home"): ["Weighted Squats", "Resistance Band Rows", "Dips"],
    ("Strength Training", "Advanced", "Home"): ["Handstand Push-ups", "One-Arm Push-ups", "Pistol Squats"]
}

# Function to get a workout plan based on user input
def get_workout(goal, level, equipment):
    return workout_plans.get((goal, level, equipment), ["Push-ups", "Planks", "Bodyweight Squats","dumbells","crunches"])  # Default plan

# Get user input
goal = input("Enter your fitness goal (Muscle Gain / Fat Loss / Endurance / Flexibility / Sports Training / Strength Training): ").strip()
level = input("Enter your fitness level (Beginner / Intermediate / Advanced): ").strip()
equipment = input("Enter available equipment (Gym / Home): ").strip()

# Get and display workout
workout_plan = get_workout(goal, level, equipment)

print("\n🏋️ Your Personalized Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")

import random

# Expanded workout plans with different goals
workout_plans = {
    "Muscle Gain": {
        "Beginner": {
            "Gym": ["Squats", "Bench Press", "Deadlifts", "Lat Pulldown", "Bicep Curls"],
            "Home": ["Push-ups", "Bodyweight Squats", "Resistance Band Rows", "Dumbbell Press"]
        },
        "Intermediate": {
            "Gym": ["Pull-ups", "Overhead Press", "Leg Press", "Dumbbell Rows", "Chest Fly"],
            "Home": ["Handstand Push-ups", "Bulgarian Split Squats", "Dumbbell Deadlifts", "Triceps Dips"]
        },
        "Advanced": {
            "Gym": ["Heavy Deadlifts", "Weighted Dips", "Front Squats", "Snatch", "Power Cleans"],
            "Home": ["One-arm Push-ups", "Pistol Squats", "Planche Push-ups", "Kettlebell Swings"]
        }
    },
    "Fat Loss": {
        "Beginner": {
            "Gym": ["Jump Rope", "Treadmill Walk", "Elliptical Trainer", "Rowing Machine"],
            "Home": ["Jump Rope", "Bodyweight Squats", "Burpees", "Jogging"]
        },
        "Intermediate": {
            "Gym": ["HIIT Workout", "Boxing Drills", "Stair Climber", "Battle Ropes"],
            "Home": ["Mountain Climbers", "Jumping Lunges", "Plank to Push-Up", "Kettlebell Swings"]
        },
        "Advanced": {
            "Gym": ["Sprint Intervals", "Heavy Kettlebell Swings", "Sled Pushes", "Tire Flips"],
            "Home": ["Sprint Drills", "Box Jumps", "Shadow Boxing", "Explosive Jump Squats"]
        }
    },
    "Endurance": {
        "Beginner": {
            "Gym": ["Rowing Machine", "Treadmill Walk", "Stationary Bike"],
            "Home": ["Jump Rope", "Brisk Walking", "Step-ups", "Light Jogging"]
        },
        "Intermediate": {
            "Gym": ["Running", "Elliptical Trainer", "Swimming", "Rowing Machine"],
            "Home": ["Cycling", "Stair Climbing", "Bodyweight Circuit", "Jump Rope"]
        },
        "Advanced": {
            "Gym": ["Marathon Training", "Sprint Intervals", "Long-distance Swimming"],
            "Home": ["Trail Running", "Hill Sprints", "High-Rep Bodyweight Training"]
        }
    },
    "Flexibility": {
        "Beginner": {
            "Gym": ["Basic Yoga Poses", "Foam Rolling", "Neck & Shoulder Stretch"],
            "Home": ["Seated Forward Bend", "Cat-Cow Stretch", "Side Lunges"]
        },
        "Intermediate": {
            "Gym": ["Dynamic Stretching", "Lunging Hip Flexor Stretch", "Cobra Pose"],
            "Home": ["Downward Dog", "Pigeon Pose", "Child’s Pose"]
        },
        "Advanced": {
            "Gym": ["Advanced Yoga", "Full Body Stretch Routine"],
            "Home": ["Frog Stretch", "Full Bridge", "Scorpion Stretch"]
        }
    },
    "Strength Training": {
        "Beginner": {
            "Gym": ["Leg Press", "Chest Press", "Seated Rows", "Overhead Dumbbell Press"],
            "Home": ["Push-ups", "Bodyweight Squats", "Planks", "Lunges"]
        },
        "Intermediate": {
            "Gym": ["Squats", "Deadlifts", "Bench Press", "Pull-ups"],
            "Home": ["Weighted Squats", "Dumbbell Rows", "Dips"]
        },
        "Advanced": {
            "Gym": ["Olympic Lifts", "Heavy Squats", "Snatch", "Power Cleans"],
            "Home": ["Handstand Push-ups", "One-arm Push-ups", "Pistol Squats"]
        }
    },
    "Sports Training": {
        "Beginner": {
            "Gym": ["Agility Ladder Drills", "Box Drills", "Resistance Band Drills"],
            "Home": ["Jump Rope", "Footwork Drills", "Core Stability Exercises"]
        },
        "Intermediate": {
            "Gym": ["Plyometric Jumps", "Sprint Drills", "Medicine Ball Throws"],
            "Home": ["Speed Drills", "Explosive Push-ups", "Dynamic Lunges"]
        },
        "Advanced": {
            "Gym": ["Explosive Sprinting", "Depth Jumps", "Olympic Weightlifting"],
            "Home": ["Power Plyometrics", "High-Intensity Sprint Training", "Advanced Agility Drills"]
        }
    }
}

# Function to get a workout plan based on user input
def get_workout(goal, level, equipment):
    return workout_plans.get(goal, {}).get(level, {}).get(equipment, ["Push-ups", "Planks", "Bodyweight Squats"])  # Default plan

# Get user input
goal = input("Enter your fitness goal (Muscle Gain / Fat Loss / Endurance / Flexibility / Strength Training / Sports Training): ").strip()
level = input("Enter your fitness level (Beginner / Intermediate / Advanced): ").strip()
equipment = input("Enter available equipment (Gym / Home): ").strip()

# Get and display workout
workout_plan = get_workout(goal, level, equipment)

print("\n🏋️ Your Personalized Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")

import random

# Expanded workout plans with different goals
workout_plans = {
    "Muscle Gain": {
        "Beginner": {
            "Gym": ["Squats", "Bench Press", "Deadlifts", "Lat Pulldown", "Bicep Curls"],
            "Home": ["Push-ups", "Bodyweight Squats", "Resistance Band Rows", "Dumbbell Press"]
        },
        "Intermediate": {
            "Gym": ["Pull-ups", "Overhead Press", "Leg Press", "Dumbbell Rows", "Chest Fly"],
            "Home": ["Handstand Push-ups", "Bulgarian Split Squats", "Dumbbell Deadlifts", "Triceps Dips"]
        },
        "Advanced": {
            "Gym": ["Heavy Deadlifts", "Weighted Dips", "Front Squats", "Snatch", "Power Cleans"],
            "Home": ["One-arm Push-ups", "Pistol Squats", "Planche Push-ups", "Kettlebell Swings"]
        }
    },
    "Fat Loss": {
        "Beginner": {
            "Gym": ["Jump Rope", "Treadmill Walk", "Elliptical Trainer", "Rowing Machine"],
            "Home": ["Jump Rope", "Bodyweight Squats", "Burpees", "Jogging"]
        },
        "Intermediate": {
            "Gym": ["HIIT Workout", "Boxing Drills", "Stair Climber", "Battle Ropes"],
            "Home": ["Mountain Climbers", "Jumping Lunges", "Plank to Push-Up", "Kettlebell Swings"]
        },
        "Advanced": {
            "Gym": ["Sprint Intervals", "Heavy Kettlebell Swings", "Sled Pushes", "Tire Flips"],
            "Home": ["Sprint Drills", "Box Jumps", "Shadow Boxing", "Explosive Jump Squats"]
        }
    },
    "Endurance": {
        "Beginner": {
            "Gym": ["Rowing Machine", "Treadmill Walk", "Stationary Bike"],
            "Home": ["Jump Rope", "Brisk Walking", "Step-ups", "Light Jogging"]
        },
        "Intermediate": {
            "Gym": ["Running", "Elliptical Trainer", "Swimming", "Rowing Machine"],
            "Home": ["Cycling", "Stair Climbing", "Bodyweight Circuit", "Jump Rope"]
        },
        "Advanced": {
            "Gym": ["Marathon Training", "Sprint Intervals", "Long-distance Swimming"],
            "Home": ["Trail Running", "Hill Sprints", "High-Rep Bodyweight Training"]
        }
    },
    "Flexibility": {
        "Beginner": {
            "Gym": ["Basic Yoga Poses", "Foam Rolling", "Neck & Shoulder Stretch"],
            "Home": ["Seated Forward Bend", "Cat-Cow Stretch", "Side Lunges"]
        },
        "Intermediate": {
            "Gym": ["Dynamic Stretching", "Lunging Hip Flexor Stretch", "Cobra Pose"],
            "Home": ["Downward Dog", "Pigeon Pose", "Child’s Pose"]
        },
        "Advanced": {
            "Gym": ["Advanced Yoga", "Full Body Stretch Routine"],
            "Home": ["Frog Stretch", "Full Bridge", "Scorpion Stretch"]
        }
    },
    "Strength Training": {
        "Beginner": {
            "Gym": ["Leg Press", "Chest Press", "Seated Rows", "Overhead Dumbbell Press"],
            "Home": ["Push-ups", "Bodyweight Squats", "Planks", "Lunges"]
        },
        "Intermediate": {
            "Gym": ["Squats", "Deadlifts", "Bench Press", "Pull-ups"],
            "Home": ["Weighted Squats", "Dumbbell Rows", "Dips"]
        },
        "Advanced": {
            "Gym": ["Olympic Lifts", "Heavy Squats", "Snatch", "Power Cleans"],
            "Home": ["Handstand Push-ups", "One-arm Push-ups", "Pistol Squats"]
        }
    },
    "Sports Training": {
        "Beginner": {
            "Gym": ["Agility Ladder Drills", "Box Drills", "Resistance Band Drills"],
            "Home": ["Jump Rope", "Footwork Drills", "Core Stability Exercises"]
        },
        "Intermediate": {
            "Gym": ["Plyometric Jumps", "Sprint Drills", "Medicine Ball Throws"],
            "Home": ["Speed Drills", "Explosive Push-ups", "Dynamic Lunges"]
        },
        "Advanced": {
            "Gym": ["Explosive Sprinting", "Depth Jumps", "Olympic Weightlifting"],
            "Home": ["Power Plyometrics", "High-Intensity Sprint Training", "Advanced Agility Drills"]
        }
    }
}

# Function to get a workout plan based on user input
def get_workout(goal, level, equipment):
    if goal in workout_plans:
        if level in workout_plans[goal]:
            if equipment in workout_plans[goal][level]:
                return workout_plans[goal][level][equipment]
    return ["Push-ups", "Planks", "Bodyweight Squats"]  # Default plan if no match

# Get user input
goal = input("Enter your fitness goal (Muscle Gain / Fat Loss / Endurance / Flexibility / Strength Training / Sports Training): ").strip()
level = input("Enter your fitness level (Beginner / Intermediate / Advanced): ").strip()
equipment = input("Enter available equipment (Gym / Home): ").strip()

# Get and display workout
workout_plan = get_workout(goal, level, equipment)

print("\n🏋️ Your Personalized Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")

import random

# Expanded workout plans with different goals
workout_plans = {
    "Muscle Gain": {
        "Beginner": {
            "Gym": ["Squats", "Bench Press", "Deadlifts", "Lat Pulldown", "Bicep Curls"],
            "Home": ["Push-ups", "Bodyweight Squats", "Resistance Band Rows", "Dumbbell Press"]
        },
        "Intermediate": {
            "Gym": ["Pull-ups", "Overhead Press", "Leg Press", "Dumbbell Rows", "Chest Fly"],
            "Home": ["Handstand Push-ups", "Bulgarian Split Squats", "Dumbbell Deadlifts", "Triceps Dips"]
        },
        "Advanced": {
            "Gym": ["Heavy Deadlifts", "Weighted Dips", "Front Squats", "Snatch", "Power Cleans"],
            "Home": ["One-arm Push-ups", "Pistol Squats", "Planche Push-ups", "Kettlebell Swings"]
        }
    },
    "Fat Loss": {
        "Beginner": {
            "Gym": ["Jump Rope", "Treadmill Walk", "Elliptical Trainer", "Rowing Machine"],
            "Home": ["Jump Rope", "Bodyweight Squats", "Burpees", "Jogging"]
        },
        "Intermediate": {
            "Gym": ["HIIT Workout", "Boxing Drills", "Stair Climber", "Battle Ropes"],
            "Home": ["Mountain Climbers", "Jumping Lunges", "Plank to Push-Up", "Kettlebell Swings"]
        },
        "Advanced": {
            "Gym": ["Sprint Intervals", "Heavy Kettlebell Swings", "Sled Pushes", "Tire Flips"],
            "Home": ["Sprint Drills", "Box Jumps", "Shadow Boxing", "Explosive Jump Squats"]
        }
    },
    "Endurance": {
        "Beginner": {
            "Gym": ["Rowing Machine", "Treadmill Walk", "Stationary Bike"],
            "Home": ["Jump Rope", "Brisk Walking", "Step-ups", "Light Jogging"]
        },
        "Intermediate": {
            "Gym": ["Running", "Elliptical Trainer", "Swimming", "Rowing Machine"],
            "Home": ["Cycling", "Stair Climbing", "Bodyweight Circuit", "Jump Rope"]
        },
        "Advanced": {
            "Gym": ["Marathon Training", "Sprint Intervals", "Long-distance Swimming"],
            "Home": ["Trail Running", "Hill Sprints", "High-Rep Bodyweight Training"]
        }
    },
    "Flexibility": {
        "Beginner": {
            "Gym": ["Basic Yoga Poses", "Foam Rolling", "Neck & Shoulder Stretch"],
            "Home": ["Seated Forward Bend", "Cat-Cow Stretch", "Side Lunges"]
        },
        "Intermediate": {
            "Gym": ["Dynamic Stretching", "Lunging Hip Flexor Stretch", "Cobra Pose"],
            "Home": ["Downward Dog", "Pigeon Pose", "Child’s Pose"]
        },
        "Advanced": {
            "Gym": ["Advanced Yoga", "Full Body Stretch Routine"],
            "Home": ["Frog Stretch", "Full Bridge", "Scorpion Stretch"]
        }
    },
    "Strength Training": {
        "Beginner": {
            "Gym": ["Leg Press", "Chest Press", "Seated Rows", "Overhead Dumbbell Press"],
            "Home": ["Push-ups", "Bodyweight Squats", "Planks", "Lunges"]
        },
        "Intermediate": {
            "Gym": ["Squats", "Deadlifts", "Bench Press", "Pull-ups"],
            "Home": ["Weighted Squats", "Dumbbell Rows", "Dips"]
        },
        "Advanced": {
            "Gym": ["Olympic Lifts", "Heavy Squats", "Snatch", "Power Cleans"],
            "Home": ["Handstand Push-ups", "One-arm Push-ups", "Pistol Squats"]
        }
    },
    "Sports Training": {
        "Beginner": {
            "Gym": ["Agility Ladder Drills", "Box Drills", "Resistance Band Drills"],
            "Home": ["Jump Rope", "Footwork Drills", "Core Stability Exercises"]
        },
        "Intermediate": {
            "Gym": ["Plyometric Jumps", "Sprint Drills", "Medicine Ball Throws"],
            "Home": ["Speed Drills", "Explosive Push-ups", "Dynamic Lunges"]
        },
        "Advanced": {
            "Gym": ["Explosive Sprinting", "Depth Jumps", "Olympic Weightlifting"],
            "Home": ["Power Plyometrics", "High-Intensity Sprint Training", "Advanced Agility Drills"]
        }
    }
}

# Function to get a workout plan based on user input
def get_workout(goal, level, equipment):
    # Convert input to title case for consistency
    goal = goal.title()
    level = level.title()
    equipment = equipment.title()

    # Check if user input exists in dictionary
    if goal in workout_plans and level in workout_plans[goal] and equipment in workout_plans[goal][level]:
        return workout_plans[goal][level][equipment]

    # If no valid selection, return a default message
    return ["⚠️ Invalid selection. Please check your inputs."]

# Get user input
print("\n🏋️ WELCOME TO YOUR AI WORKOUT PLANNER! 🏋️")
goal = input("\nEnter your fitness goal (Muscle Gain / Fat Loss / Endurance / Flexibility / Strength Training / Sports Training): ").strip()
level = input("Enter your fitness level (Beginner / Intermediate / Advanced): ").strip()
equipment = input("Enter available equipment (Gym / Home): ").strip()

# Get and display workout
workout_plan = get_workout(goal, level, equipment)

print("\n🏋️ Your Personalized Workout Plan:")
for exercise in workout_plan:
    print(f"- {exercise}")